version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_tienda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3306:3306"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    container_name: tienda_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: usuario123
      DB_NAME: SHOP
    ports:
      - "3101:3101"
    depends_on:
      - db

volumes:
  db_data:
  app_data:
