version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_tienda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3306:3306"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  users_app:
    build: ./services/users
    container_name: users_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: usuario123
      DB_NAME: tienda
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./services/users/src:/app/src

  products_app:
    build: ./services/products
    container_name: products_app_1
    restart: always
    environment:
      DB_HOST: db
      DB_USER: usuario        
      DB_PASSWORD: usuario123  
      DB_NAME: tienda        
      PORT: 3002
    depends_on:
      - db

  orders_app:
    build: ./services/orders
    container_name: orders_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: usuario123
      DB_NAME: tienda
      PORT: 3003
    ports:
    - "3003:3003"
    depends_on:
    - db
    volumes:
    - ./services/orders/src:/app/src

  nginx_gateway:
    build: ./nginx
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"
    depends_on:
      - users_app
      - products_app
      - orders_app

volumes:
  db_data:
