services:
  db:
    image: mysql:8.0
    container_name: mysql_tienda
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
